[package]
name = "poc_turtle"
version = "0.1.0"
authors = ["Gaël <g.batault@citegestion.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turtle = "1.0.0-rc.3"